#!/bin/sh

case "$1" in
  start)
    echo "Starting K1 Backup..."
    /usr/data/K1-Backup/K1-Backup.sh -b "$BRANCH" -t "$IFS" -g origin & > /dev/null
    ;;
  stop)
    echo "Stopping K1 Backup..."
    pkill K1
    pkill inotifywait
    ;;
  restart)
    echo "Restarting K1 Backup..."
    pkill K1
    pkill inotify
    sleep 1
     /usr/data/K1-Backup/K1-Backup.sh -b "$BRANCH" -t "$IFS" -g origin & > /dev/null
    ;;
  *)
    Usage: $0 {start|stop|restart}
    exit 1
    ;;
esac
exit 0
